version: '3'

services:
  db:
    container_name: db
    image: postgres:10.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    container_name: app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/src
      - ipython_data_local:/root/.ipython/profile_default
    build:
      context: .
      dockerfile: cs_manager/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  ipython_data_local: {}
